version: '3.8'
 
services:
  glance-agent:
    build: .
    container_name: glance-serverstatus-agent
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN:-glance_agent_token}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Authorization: Bearer ${SECRET_TOKEN:-glance_agent_token}", "http://localhost:8080/api/sysinfo/all"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"